### ISSUE TITLE
Add link for the presentation in What is ros2_control.

### ISSUE THREAD

**Issue by Xi-HHHM** [ros-controls/roscon2022_workshop#1]
A link for more details needs to be added at the end of [what is ros2_control](https://github.com/ros-controls/roscon2022_workshop#what-is-ros2_control)

**Comment by bmagyar** [comment]
CNA you open a PR for it?

**Comment by destogl** [comment]
Please add this link there: https://control.ros.org/master/doc/resources/resources.html#ros-world-2021
