### ISSUE TITLE
Task 8: Controller configuration is empty

### ISSUE THREAD

**Issue by Xi-HHHM** [ros-controls/roscon2022_workshop#16]
The configuration file `soho-12_controllers.yaml` for the controller in the package `controlko_bringup` is empty in all three branches (mater, task, and solution).

It causes the following problem while launching the test:

> [ros2_control_node-1] [ERROR] [1677429499.879219694] [controller_manager]: The 'type' param was not defined for 'joint_state_broadcaster'.
[spawner-3] [FATAL] [1677429499.880274216] [spawner_joint_state_broadcaster]: Failed loading controller joint_state_broadcaster 
[ros2_control_node-1] [ERROR] [1677429503.748211370] [controller_manager]: The 'type' param was not defined for 'displacement_controller'.
[spawner-5] [FATAL] [1677429503.748720147] [spawner_displacement_controller]: Failed loading controller displacement_controller

**Comment by destogl** [comment]
@Xi-HHHM can you please do following changes and open PRs for tasks and solution:

1. Use RRBot instead of Solo-12
2. Solution for RRBot with parameterization of controller.

**Comment by destogl** [comment]
merged manually and done
