### ISSUE TITLE
Package ros-rolling-ur-moveit-config has been removed

### ISSUE THREAD

**Issue by Xi-HHHM** [ros-controls/roscon2022_workshop#2]
Source: https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2023-01-06/29094

Therefore, installing the repo using `rosdep install -y -i --from-paths .` is not completely successful.

**Comment by Xi-HHHM** [comment]
Suggestion: use `ros-rolling-ur-bringup` instead

**Comment by bmagyar** [comment]
Open a PR with the suggestions please

**Comment by Xi-HHHM** [comment]
Hi, I tracked the dependency and found it in the repo [Universal_Robots_ROS2_Ignition_Simulation](https://github.com/UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation). Maybe we should add an issue there.

**Comment by destogl** [comment]
Please remove “UR simulation” dependency. It is not needed for now.
